# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: development
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000


















# apiVersion: v1
# kind: Service
# metadata:
#   name: user-service
#   namespace: development
# spec:
#   selector:
#     app: user-service
#   ports:
#     - protocol: TCP
#       port: 100
#       targetPort: 3000
#   type: NodePort
