# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: identity-provider-service
  namespace: development
spec:
  selector:
    app: identity-provider-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000