apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: development
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 100
      targetPort: 4000
  type: LoadBalancer
